<a href="https://colab.research.google.com/github/Febrian-chiperbase/Getting-Started-with-Python/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("hello wordl")

hello wordl


In [ ]:
import time

In [ ]:
print (time.ctime())

Thu Feb  6 04:41:44 2025


**testing python**

In [ ]:
z = 30
y = 20.5
c = "hii"
d = "hello", "holla"

y,z,c,d

print (z,y,c,d)

30 20.5 hii ('hello', 'holla')


In [ ]:
o = int(1)
y = int(30.3)
z = int("3")
j = str(30)

print(o,y,z,j)

1 30 3 30


In [ ]:
a = "haloo"
b = " lohh"
c = a+b
print (c)

haloo lohh


In [ ]:
a = "Hello wordl"

print (a[6])
print (len(a))

w
11


In [ ]:
a = "binus university"

print (a[2:5])
print (a[6:])
print (a[:5])

nus
university
binus


In [ ]:
contry = "india"

print (contry.upper())
print (contry.upper())
print (contry.replace("ia", "o"))

INDIA
INDIA
indo


In [ ]:
from os.path import samefile
a = "sam"
b = 50
c = "nama saya {} umur saya {}"
print(c,a,b)

nama saya {} umur saya {} sam 50


In [ ]:
nama = "anom"
for i, char in enumerate(nama):
  print(i, char)

0 a
1 n
2 o
3 m


In [ ]:

def perbandingan(a,b):
  if a < b:
    print("a kurang dari b") # Indented with 4 spaces
  if a > b:
    print("a lebih dari b") # Indented with 4 spaces
  if a == b:
    print("a sama dengan b")

perbandingan(8,8)

a sama dengan b


In [ ]:
i = 2
while i<9:
  print(i)
  i += 1


2
3
4
5
6
7
8


In [ ]:
i = 1

for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for o in range(1,10):
  if o % 2 == 0:
    print("ganjil")
  elif o % 2 == 1:
    print("genap")

genap
ganjil
genap
ganjil
genap
ganjil
genap
ganjil
genap


In [ ]:
import numpy as np



In [ ]:
x = np.array([[1,2,3],[3,5,6]])
x

array([[1, 2, 3],
       [3, 5, 6]])

In [ ]:
y = np.array([[1,7,9],[6,2,8]])
y

array([[1, 7, 9],
       [6, 2, 8]])

In [ ]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 2  9 12]
 [ 9  7 14]]
[[ 0 -5 -6]
 [-3  3 -2]]
[[ 1 14 27]
 [18 10 48]]
[[1.         0.28571429 0.33333333]
 [0.5        2.5        0.75      ]]


In [ ]:
del print
data = np.array([1,2,3,6,7,8,9,43])
print("rata rata", np.mean(data))
print("standar deviasi", np.std(data))
print("max", np.max(data))
print("min", np.min(data))

rata rata 9.875
standar deviasi 12.810518139404042
max 43
min 1
